<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Bob" name="Extent Report" tests="3" failures="1" timestamp="15 Dec 2017 19:24:49 GMT" time="1.263" errors="0">
  <testcase name="failTest" time="0.02" classname="SeleniumTraining.PHP.ExtentReportsClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at SeleniumTraining.PHP.ExtentReportsClass.failTest(ExtentReportsClass.java:42)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase name="passTest" time="0.0" classname="SeleniumTraining.PHP.ExtentReportsClass"/>
  <testcase name="skipTest" time="0.004" classname="SeleniumTraining.PHP.ExtentReportsClass">
    <skipped/>
  </testcase> <!-- skipTest -->
</testsuite> <!-- Extent Report -->
